vim.opt.runtimepath:prepend(vim.fn.getcwd())
local stringer = require('stringer')
stringer.setup({ storage_dir = vim.env.STRINGER_REOPEN_DIR })
assert(stringer.open('demo'))
assert(stringer.next())
assert(vim.api.nvim_buf_get_name(0) == vim.env.STRINGER_REOPEN_FILE)
assert(vim.api.nvim_win_get_cursor(0)[1] == 2)
assert(stringer.next())
assert(vim.api.nvim_win_get_cursor(0)[1] == 3)
print('REOPEN PASS')
vim.cmd('qa!')
