vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd('runtime plugin/stringer.lua')
local s = require('stringer')
local codec = require('stringer.codec')
local store = require('stringer.store')
local state = require('stringer.state')
local pane = require('stringer.pane')
local uv = vim.uv or vim.loop
local cwd = vim.fn.getcwd()
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
root = assert(uv.fs_realpath(root))
local passed, failed = 0, 0
local dir, file, other
local messages = {}
vim.notify = function(message) messages[#messages + 1] = message end

local function eq(a, b)
  assert(vim.deep_equal(a, b), ('expected %s, got %s'):format(vim.inspect(b), vim.inspect(a)))
end
local function yes(ok, err) assert(ok, tostring(err)); return ok end
local function no(ok, err) assert(not ok, 'Expected failure: ' .. tostring(err)) end
local function edit(path, line)
  local buf = vim.fn.bufadd(path)
  vim.fn.bufload(buf)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_win_set_cursor(0, { line or 1, 0 })
end
local function reset()
  vim.o.hidden = true
  vim.cmd('silent! tabonly!')
  vim.cmd('silent! only!')
  vim.cmd('enew!')
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if buf ~= vim.api.nvim_get_current_buf() then vim.api.nvim_buf_delete(buf, { force = true }) end
  end
  state.active, state.windows = nil, {}
  pane.buffers, pane.windows = {}, {}
  vim.api.nvim_set_current_dir(cwd)
  dir = root .. '/' .. (passed + failed + 1)
  vim.fn.mkdir(dir .. '/repo-a', 'p')
  vim.fn.mkdir(dir .. '/repo-b', 'p')
  file, other = dir .. '/repo-a/a "quoted" file.lua', dir .. '/repo-b/b.lua'
  vim.fn.writefile({ 'one', 'two', 'three', 'four' }, file)
  vim.fn.writefile({ 'alpha', 'beta', 'gamma' }, other)
  s.setup({ storage_dir = dir .. '/paths', pane_width = 48 })
  messages = {}
end
local function test(name, fn)
  local ok, err = xpcall(function() reset(); fn() end, debug.traceback)
  if ok then passed = passed + 1; print('PASS ' .. name)
  else failed = failed + 1; print('FAIL ' .. name .. '\n' .. err) end
end
local function capture()
  yes(s.new('demo'))
  edit(file, 2); yes(s.add())
  edit(other, 3); yes(s.add())
  edit(file, 4); yes(s.add())
  return state.active
end
local function rows(record)
  return vim.api.nvim_buf_get_lines(pane.buffer(record), 0, -1, false)
end

test('version 1 format round trips escaped paths and duplicates', function()
  local marks = { { file = file, line = 2 }, { file = file, line = 2 } }
  eq(codec.decode(codec.lines(codec.text(codec.encode(marks)))), marks)
  eq(codec.decode(codec.encode({})), {})
end)
test('invalid records and versions report their exact line numbers', function()
  local marks, errors = codec.decode({ '{"type":"stringer","format_version":2,"mark_version":1}', '',
    '{"file":"relative","line":1}', '{"file":"/a","line":1.5}', 'null', '[]',
    '{"file":"/a","line":1,"extra":true}' })
  eq(marks, nil); eq(#errors, 7)
  for i, err in ipairs(errors) do eq(err.line, i) end
  no(codec.decode(codec.lines(codec.text(codec.encode({})) .. '\n')))
end)
test('storage lists paths and rejects invalid names and duplicate creation', function()
  eq(store.list(), {})
  yes(store.create('z')); yes(store.create('a'))
  eq(store.list(), { 'a', 'z' })
  no(store.create('../bad')); no(store.create('z'))
end)
test('commands complete and reject unexpected arguments', function()
  vim.cmd('Stringer new demo')
  eq(vim.fn.getcompletion('Stringer op', 'cmdline'), { 'open' })
  eq(vim.fn.getcompletion('Stringer open d', 'cmdline'), { 'demo' })
  eq(vim.fn.getcompletion('Stringer move-', 'cmdline'), { 'move-up', 'move-down' })
  vim.cmd('Stringer next unexpected')
  assert(messages[#messages]:find('Usage'))
end)
test('nearest-line selection updates on cursor and file changes', function()
  local r = capture()
  eq(r.index, 3)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  vim.api.nvim_exec_autocmds('CursorMoved', {})
  eq(r.index, 1)
  edit(other, 1); s.sync(); eq(r.index, 2)
  vim.cmd('enew'); s.sync(); eq(r.index, 2)
end)
test('ties keep the active mark, otherwise choose earlier codepath entry', function()
  local r = capture()
  vim.api.nvim_win_set_cursor(0, { 3, 0 })
  s.sync(); eq(r.index, 3)
  r.index = 2; s.sync(); eq(r.index, 1)
end)
test('next and previous cycle using the nearest current location', function()
  local r = capture()
  yes(s.next()); eq(r.index, 1); eq(vim.api.nvim_win_get_cursor(0)[1], 2)
  yes(s.prev()); eq(r.index, 3)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  yes(s.next()); eq(r.index, 2); eq(vim.api.nvim_buf_get_name(0), other)
end)
test('empty, single-mark, and no-current-mark navigation', function()
  no(s.next()); yes(s.new('demo')); no(s.next())
  edit(file); yes(s.add()); yes(s.next()); yes(s.prev()); eq(state.active.index, 1)
  vim.cmd('enew'); state.active.index = nil
  yes(s.prev()); eq(state.active.index, 1)
end)
test('identical locations remain independently navigable', function()
  yes(s.new('demo')); edit(file, 2); yes(s.add()); yes(s.add())
  yes(s.next()); eq(state.active.index, 2)
  s.sync(); eq(state.active.index, 2)
  yes(s.next()); eq(state.active.index, 1)
end)
test('capture rejects unnamed, unsaved and pane buffers', function()
  yes(s.new('demo')); no(s.add())
  vim.api.nvim_buf_set_name(0, dir .. '/unsaved.lua'); no(s.add())
  yes(s.show()); no(s.add()); eq(#state.active.marks, 0)
end)
test('pane is noneditable and navigation preserves the code window', function()
  local r = capture()
  local codewin = vim.api.nvim_get_current_win()
  yes(s.show())
  local win, buf = vim.api.nvim_get_current_win(), pane.buffer(r)
  eq(vim.bo[buf].modifiable, false); eq(vim.bo[buf].buftype, 'nofile')
  no(pcall(vim.api.nvim_buf_set_lines, buf, 0, 1, false, { 'bad' }))
  yes(s.jump(1)); eq(vim.api.nvim_get_current_win(), codewin)
  eq(vim.api.nvim_win_get_buf(win), buf)
  local marks = vim.api.nvim_buf_get_extmarks(buf, pane.namespace, 0, -1, {})
  eq(#marks, 1); eq(marks[1][2], pane.first_mark_line - 1)
end)
test('moving marks saves immediately and preserves active entry identity', function()
  local r = capture(); yes(s.jump(1)); yes(s.show())
  vim.api.nvim_win_set_cursor(0, { 3, 0 })
  yes(s.move_down()); eq(r.index, 2); eq(r.marks[2].line, 2)
  eq(vim.api.nvim_win_get_cursor(0)[1], 4)
  eq(store.load('demo').marks, r.marks)
  yes(s.move_up()); eq(r.index, 1)
  no(s.move_up(1)); no(s.move_down(3))
end)
test('remove and undo persist, including deleting the last remaining mark', function()
  local r = capture(); yes(s.jump(1)); yes(s.show())
  yes(s.remove(1)); eq(r.index, nil); eq(#r.marks, 2)
  yes(s.undo()); eq(r.index, 1); eq(#r.marks, 3)
  eq(store.load('demo').marks, r.marks)
  yes(s.remove(3)); yes(s.remove(2)); yes(s.remove(1))
  eq(#store.load('demo').marks, 0); no(s.next())
  yes(s.undo()); eq(#store.load('demo').marks, 1)
end)
test('pane header actions do not remove an active mark accidentally', function()
  local r = capture(); yes(s.show())
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  no(s.remove()); no(s.move_down()); eq(#r.marks, 3)
end)
test('failed persistence preserves disk, model, history and view', function()
  local r = capture(); yes(s.show())
  local text, view, history = r.text, rows(r), #r.history
  local original = uv.fs_rename
  uv.fs_rename = function() return nil, 'injected failure' end
  local ok, err = pcall(function()
    no(s.remove(1)); no(s.move_down(1)); no(s.undo())
    eq(r.text, text); eq(store.read(r.file), text); eq(rows(r), view); eq(#r.history, history)
    eq(#vim.fn.glob(r.file .. '.*', false, true), 0)
  end)
  uv.fs_rename = original; yes(ok, err)
end)
test('external edits block mutations until reload and clear undo history', function()
  local r = capture()
  local replacement = { { file = other, line = 1 } }
  vim.fn.writefile(codec.encode(replacement), r.file)
  no(s.add()); no(s.remove(1)); no(s.rename('renamed')); no(s.undo())
  yes(s.reload()); eq(state.active.marks, replacement); no(s.undo())
end)
test('invalid external file load preserves current valid state', function()
  local r = capture()
  vim.fn.writefile({ 'invalid' }, r.file)
  no(s.reload()); eq(state.active, r)
  no(s.open('missing')); eq(state.active, r)
end)
test('raw file drafts are protected from mutations and activation', function()
  local r = capture()
  edit(r.file); vim.api.nvim_buf_set_lines(0, 1, 2, false, { 'draft' })
  no(s.remove(1)); no(s.open('demo')); no(s.rename('renamed'))
  eq(vim.api.nvim_buf_get_lines(0, 1, 2, false), { 'draft' })
end)
test('rename updates storage, pane and future writes without changing marks', function()
  local r = capture(); yes(s.show())
  local old, buf, index = r.file, pane.buffer(r), r.index
  yes(s.rename('renamed')); eq(store.read(old), nil)
  eq(r.name, 'renamed'); eq(r.index, index); eq(pane.buffer(r), buf)
  assert(rows(r)[1]:find('renamed'))
  yes(s.remove(1)); eq(store.load('renamed').marks, r.marks)
  yes(s.undo()); eq(#store.load('renamed').marks, 3)
end)
test('rename rejects duplicates and invalid names', function()
  local r = capture(); yes(store.create('taken'))
  no(s.rename('taken')); no(s.rename('../bad'))
  eq(r.name, 'demo'); eq(#store.load('taken').marks, 0)
  yes(s.rename('demo')); eq(#store.load('demo').marks, 3)
end)
test('rename rolls back the new name if removing old name fails', function()
  local r = capture()
  local original = uv.fs_unlink
  uv.fs_unlink = function(path)
    if path == r.file then return nil, 'injected unlink failure' end
    return original(path)
  end
  local ok, err = pcall(function()
    no(s.rename('renamed')); eq(r.name, 'demo')
    eq(store.list(), { 'demo' }); eq(store.read(r.file), r.text)
  end)
  uv.fs_unlink = original; yes(ok, err)
end)
test('empty picker prompts to create and cancellation is harmless', function()
  local original = vim.ui.input
  local ok, err = pcall(function()
    vim.ui.input = function(_, callback) callback(nil) end
    yes(s.open()); eq(state.active, nil); eq(store.list(), {})
    vim.ui.input = function(_, callback) callback('created') end
    yes(s.open()); eq(state.active.name, 'created')
  end)
  vim.ui.input = original; yes(ok, err)
end)
test('picker selection and asynchronous rename target the correct path', function()
  yes(s.new('a')); yes(s.new('b'))
  local original_select, original_input = vim.ui.select, vim.ui.input
  local ok, err = pcall(function()
    vim.ui.select = function(items, _, cb) eq(items, { 'a', 'b' }); cb('a') end
    yes(s.open()); eq(state.active.name, 'a')
    local callback
    vim.ui.input = function(_, cb) callback = cb end
    yes(s.rename()); yes(s.open('b')); callback('wrong')
    eq(store.list(), { 'a', 'b' })
  end)
  vim.ui.select, vim.ui.input = original_select, original_input; yes(ok, err)
end)
test('project paths use cwd Git root, including worktree .git files', function()
  vim.fn.mkdir(dir .. '/repo-a/sub', 'p')
  vim.fn.writefile({ 'gitdir: somewhere' }, dir .. '/repo-a/.git')
  vim.api.nvim_set_current_dir(dir .. '/repo-a/sub')
  eq(pane.project_root(), dir .. '/repo-a')
  eq(pane.display_path(file), 'a "quoted" file.lua')
  local home = vim.fs.normalize(vim.fn.expand('~'))
  eq(pane.display_path(home .. '/elsewhere/file.lua'), '~/elsewhere/file.lua')
  eq(pane.display_path('/outside/home/file.lua'), '/outside/home/file.lua')
  eq(pane.display_path('/work/stringer-extra/a', '/work/stringer'), '/work/stringer-extra/a')
end)
test('cwd changes rerender the pane and navigation does not change display root', function()
  local r = capture(); yes(s.show())
  vim.api.nvim_set_current_dir(dir .. '/repo-a')
  assert(rows(r)[3]:find('1  a "quoted" file.lua:2', 1, true))
  yes(s.jump(2)); yes(s.show())
  assert(rows(r)[3]:find('1  a "quoted" file.lua:2', 1, true))
end)
test('missing and stale targets preserve active state', function()
  local r = capture(); yes(s.jump(1))
  vim.fn.delete(other); no(s.next()); eq(r.index, 1)
  vim.api.nvim_buf_set_lines(0, 2, -1, false, {})
  no(s.jump(3)); eq(r.index, 1)
end)
test('modified code obeys nohidden safeguards', function()
  local r = capture(); yes(s.jump(1)); vim.o.hidden = false
  vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'draft' })
  no(s.next()); eq(r.index, 1); eq(vim.api.nvim_buf_get_name(0), file)
  vim.o.hidden = true; yes(s.next()); eq(vim.bo[vim.fn.bufnr(file)].modified, true)
end)
test('pane retains most recent code window and fails with no code windows', function()
  capture(); vim.cmd('botright vsplit')
  local win = vim.api.nvim_get_current_win()
  yes(s.show()); yes(s.next()); eq(vim.api.nvim_get_current_win(), win)
  yes(s.show()); vim.cmd('only'); no(s.next())
end)
test('pane window selection stays within current tab and reuses buffers', function()
  local r = capture(); yes(s.show()); local buf = pane.buffer(r)
  vim.cmd('tabnew'); edit(other)
  local win = vim.api.nvim_get_current_win()
  yes(s.show()); yes(s.next()); eq(vim.api.nvim_get_current_win(), win)
  yes(s.open('demo')); eq(pane.buffer(state.active), buf)
end)
test('version 1 persisted paths reopen in a fresh Neovim process', function()
  capture()
  vim.env.STRINGER_REOPEN_DIR, vim.env.STRINGER_REOPEN_FILE = dir .. '/paths', file
  local output = vim.fn.system({ vim.v.progpath, '--headless', '-u', 'NONE', '-l', 'tests/reopen.lua' })
  assert(vim.v.shell_error == 0, output); assert(output:find('REOPEN PASS'), output)
end)

vim.api.nvim_set_current_dir(cwd)
vim.fn.delete(root, 'rf')
print(('%d passed, %d failed'):format(passed, failed))
vim.cmd(failed == 0 and 'qa!' or 'cquit 1')
