vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd('runtime plugin/stringer.lua')
local s = require('stringer')
local codec = require('stringer.codec')
local store = require('stringer.store')
local state = require('stringer.state')
local pane = require('stringer.pane')
local uv = vim.uv or vim.loop
local cwd = vim.fn.getcwd()
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
root = assert(uv.fs_realpath(root))
local passed, failed = 0, 0
local dir, file, other
local messages = {}
vim.notify = function(message) messages[#messages + 1] = message end

local function eq(a, b)
  assert(vim.deep_equal(a, b), ('expected %s, got %s'):format(vim.inspect(b), vim.inspect(a)))
end
local function yes(ok, err) assert(ok, tostring(err)); return ok end
local function no(ok, err) assert(not ok, 'Expected failure: ' .. tostring(err)) end
local function edit(path, line)
  local buf = vim.fn.bufadd(path)
  vim.fn.bufload(buf)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_win_set_cursor(0, { line or 1, 0 })
end
local function reset()
  require('stringer.import').cancel()
  vim.o.hidden = true
  vim.cmd('silent! tabonly!')
  vim.cmd('silent! only!')
  vim.cmd('enew!')
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if buf ~= vim.api.nvim_get_current_buf() then vim.api.nvim_buf_delete(buf, { force = true }) end
  end
  state.active, state.windows = nil, {}
  pane.buffers, pane.windows = {}, {}
  vim.api.nvim_set_current_dir(cwd)
  dir = root .. '/' .. (passed + failed + 1)
  vim.fn.mkdir(dir .. '/repo-a', 'p')
  vim.fn.mkdir(dir .. '/repo-b', 'p')
  file, other = dir .. '/repo-a/a "quoted" file.lua', dir .. '/repo-b/b.lua'
  vim.fn.writefile({ 'one', 'two', 'three', 'four' }, file)
  vim.fn.writefile({ 'alpha', 'beta', 'gamma' }, other)
  s.setup({ storage_dir = dir .. '/paths', pane_width = 48, gutter = true, inline_notes = true,
    symbol_labels = true, gutter_sign = 'o', gutter_note_sign = 'N', gutter_priority = 10 })
  messages = {}
end
local function test(name, fn)
  local ok, err = xpcall(function() reset(); fn() end, debug.traceback)
  if ok then passed = passed + 1; print('PASS ' .. name)
  else failed = failed + 1; print('FAIL ' .. name .. '\n' .. err) end
end
local function capture()
  yes(s.new('demo'))
  edit(file, 2); yes(s.add())
  edit(other, 3); yes(s.add())
  edit(file, 4); yes(s.add())
  return state.active
end
local function rows(record)
  return vim.api.nvim_buf_get_lines(pane.buffer(record), 0, -1, false)
end

test('mark format round trips escaped paths and duplicates', function()
  local marks = { { file = file, line = 2 }, { file = file, line = 2 } }
  eq(codec.decode(codec.lines(codec.text(codec.encode(marks)))), marks)
  eq(codec.decode(codec.encode({})), {})
end)
test('invalid records and versions report their exact line numbers', function()
  local marks, errors = codec.decode({ '{"type":"stringer","format_version":2,"mark_version":1}', '',
    '{"file":"relative","line":1}', '{"file":"/a","line":1.5}', 'null', '[]',
    '{"file":"/a","line":1,"extra":true}' })
  eq(marks, nil); eq(#errors, 7)
  for i, err in ipairs(errors) do eq(err.line, i) end
  no(codec.decode(codec.lines(codec.text(codec.encode({})) .. '\n')))
end)
test('storage lists paths and rejects invalid names and duplicate creation', function()
  eq(store.list(), {})
  yes(store.create('z')); yes(store.create('a'))
  eq(store.list(), { 'a', 'z' })
  no(store.create('../bad')); no(store.create('z'))
end)
test('commands complete and reject unexpected arguments', function()
  vim.cmd('Stringer new demo')
  eq(vim.fn.getcompletion('Stringer op', 'cmdline'), { 'open' })
  eq(vim.fn.getcompletion('Stringer open d', 'cmdline'), { 'demo' })
  eq(vim.fn.getcompletion('Stringer move-', 'cmdline'), { 'move-up', 'move-down' })
  vim.cmd('Stringer next unexpected')
  assert(messages[#messages]:find('Usage'))
end)
test('nearest-line selection updates on cursor and file changes', function()
  local r = capture()
  eq(r.index, 3)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  vim.api.nvim_exec_autocmds('CursorMoved', {})
  eq(r.index, 1)
  edit(other, 1); s.sync(); eq(r.index, 2)
  vim.cmd('enew'); s.sync(); eq(r.index, 2)
end)
test('ties keep the active mark, otherwise choose earlier codepath entry', function()
  local r = capture()
  vim.api.nvim_win_set_cursor(0, { 3, 0 })
  s.sync(); eq(r.index, 3)
  r.index = 2; s.sync(); eq(r.index, 1)
end)
test('next and previous cycle using the nearest current location', function()
  local r = capture()
  yes(s.next()); eq(r.index, 1); eq(vim.api.nvim_win_get_cursor(0)[1], 2)
  yes(s.prev()); eq(r.index, 3)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  yes(s.next()); eq(r.index, 2); eq(vim.api.nvim_buf_get_name(0), other)
end)
test('empty, single-mark, and no-current-mark navigation', function()
  no(s.next()); yes(s.new('demo')); no(s.next())
  edit(file); yes(s.add()); yes(s.next()); yes(s.prev()); eq(state.active.index, 1)
  vim.cmd('enew'); state.active.index = nil
  yes(s.prev()); eq(state.active.index, 1)
end)
test('identical locations remain independently navigable', function()
  yes(s.new('demo')); edit(file, 2); yes(s.add()); yes(s.add())
  yes(s.next()); eq(state.active.index, 2)
  s.sync(); eq(state.active.index, 2)
  yes(s.next()); eq(state.active.index, 1)
end)
test('capture rejects unnamed, unsaved and pane buffers', function()
  yes(s.new('demo')); no(s.add())
  vim.api.nvim_buf_set_name(0, dir .. '/unsaved.lua'); no(s.add())
  yes(s.show()); no(s.add()); eq(#state.active.marks, 0)
end)
test('pane is noneditable and navigation preserves the code window', function()
  local r = capture()
  local codewin = vim.api.nvim_get_current_win()
  yes(s.show())
  local win, buf = vim.api.nvim_get_current_win(), pane.buffer(r)
  eq(vim.bo[buf].modifiable, false); eq(vim.bo[buf].buftype, 'nofile')
  no(pcall(vim.api.nvim_buf_set_lines, buf, 0, 1, false, { 'bad' }))
  yes(s.jump(1)); eq(vim.api.nvim_get_current_win(), codewin)
  eq(vim.api.nvim_win_get_buf(win), buf)
  local marks = vim.api.nvim_buf_get_extmarks(buf, pane.namespace, 0, -1, {})
  eq(#marks, 2); eq(marks[1][2], pane.first_mark_line - 1)
end)
test('moving marks saves immediately and preserves active entry identity', function()
  local r = capture(); yes(s.jump(1)); yes(s.show())
  vim.api.nvim_win_set_cursor(0, { 3, 0 })
  yes(s.move_down()); eq(r.index, 2); eq(r.marks[2].line, 2)
  eq(vim.api.nvim_win_get_cursor(0)[1], 5)
  eq(store.load('demo').marks, r.marks)
  yes(s.move_up()); eq(r.index, 1)
  no(s.move_up(1)); no(s.move_down(3))
end)
test('remove and undo persist, including deleting the last remaining mark', function()
  local r = capture(); yes(s.jump(1)); yes(s.show())
  yes(s.remove(1)); eq(r.index, nil); eq(#r.marks, 2)
  yes(s.undo()); eq(r.index, 1); eq(#r.marks, 3)
  eq(store.load('demo').marks, r.marks)
  yes(s.remove(3)); yes(s.remove(2)); yes(s.remove(1))
  eq(#store.load('demo').marks, 0); no(s.next())
  yes(s.undo()); eq(#store.load('demo').marks, 1)
end)
test('pane header actions do not remove an active mark accidentally', function()
  local r = capture(); yes(s.show())
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  no(s.remove()); no(s.move_down()); eq(#r.marks, 3)
end)
test('failed persistence preserves disk, model, history and view', function()
  local r = capture(); yes(s.show())
  local text, view, history = r.text, rows(r), #r.history
  local original = uv.fs_rename
  uv.fs_rename = function() return nil, 'injected failure' end
  local ok, err = pcall(function()
    no(s.remove(1)); no(s.move_down(1)); no(s.undo())
    eq(r.text, text); eq(store.read(r.file), text); eq(rows(r), view); eq(#r.history, history)
    eq(#vim.fn.glob(r.file .. '.*', false, true), 0)
  end)
  uv.fs_rename = original; yes(ok, err)
end)
test('external edits block mutations until reload and clear undo history', function()
  local r = capture()
  local replacement = { { file = other, line = 1 } }
  vim.fn.writefile(codec.encode(replacement), r.file)
  no(s.add()); no(s.remove(1)); no(s.rename('renamed')); no(s.undo())
  yes(s.reload()); eq(state.active.marks, replacement); no(s.undo())
end)
test('invalid external file load preserves current valid state', function()
  local r = capture()
  vim.fn.writefile({ 'invalid' }, r.file)
  no(s.reload()); eq(state.active, r)
  no(s.open('missing')); eq(state.active, r)
end)
test('raw file drafts are protected from mutations and activation', function()
  local r = capture()
  edit(r.file); vim.api.nvim_buf_set_lines(0, 1, 2, false, { 'draft' })
  no(s.remove(1)); no(s.open('demo')); no(s.rename('renamed'))
  eq(vim.api.nvim_buf_get_lines(0, 1, 2, false), { 'draft' })
end)
test('rename updates storage, pane and future writes without changing marks', function()
  local r = capture(); yes(s.show())
  local old, buf, index = r.file, pane.buffer(r), r.index
  yes(s.rename('renamed')); eq(store.read(old), nil)
  eq(r.name, 'renamed'); eq(r.index, index); eq(pane.buffer(r), buf)
  assert(rows(r)[1]:find('renamed'))
  yes(s.remove(1)); eq(store.load('renamed').marks, r.marks)
  yes(s.undo()); eq(#store.load('renamed').marks, 3)
end)
test('rename rejects duplicates and invalid names', function()
  local r = capture(); yes(store.create('taken'))
  no(s.rename('taken')); no(s.rename('../bad'))
  eq(r.name, 'demo'); eq(#store.load('taken').marks, 0)
  yes(s.rename('demo')); eq(#store.load('demo').marks, 3)
end)
test('rename rolls back the new name if removing old name fails', function()
  local r = capture()
  local original = uv.fs_unlink
  uv.fs_unlink = function(path)
    if path == r.file then return nil, 'injected unlink failure' end
    return original(path)
  end
  local ok, err = pcall(function()
    no(s.rename('renamed')); eq(r.name, 'demo')
    eq(store.list(), { 'demo' }); eq(store.read(r.file), r.text)
  end)
  uv.fs_unlink = original; yes(ok, err)
end)
test('empty picker prompts to create and cancellation is harmless', function()
  local original = vim.ui.input
  local ok, err = pcall(function()
    vim.ui.input = function(_, callback) callback(nil) end
    yes(s.open()); eq(state.active, nil); eq(store.list(), {})
    vim.ui.input = function(_, callback) callback('created') end
    yes(s.open()); eq(state.active.name, 'created')
  end)
  vim.ui.input = original; yes(ok, err)
end)
test('picker selection and asynchronous rename target the correct path', function()
  yes(s.new('a')); yes(s.new('b'))
  local original_select, original_input = vim.ui.select, vim.ui.input
  local ok, err = pcall(function()
    vim.ui.select = function(items, _, cb) eq(items, { 'a', 'b' }); cb('a') end
    yes(s.open()); eq(state.active.name, 'a')
    local callback
    vim.ui.input = function(_, cb) callback = cb end
    yes(s.rename()); yes(s.open('b')); callback('wrong')
    eq(store.list(), { 'a', 'b' })
  end)
  vim.ui.select, vim.ui.input = original_select, original_input; yes(ok, err)
end)
test('project paths use cwd Git root, including worktree .git files', function()
  vim.fn.mkdir(dir .. '/repo-a/sub', 'p')
  vim.fn.writefile({ 'gitdir: somewhere' }, dir .. '/repo-a/.git')
  vim.api.nvim_set_current_dir(dir .. '/repo-a/sub')
  eq(pane.project_root(), dir .. '/repo-a')
  eq(pane.display_path(file), 'a "quoted" file.lua')
  local home = vim.fs.normalize(vim.fn.expand('~'))
  eq(pane.display_path(home .. '/elsewhere/file.lua'), '~/elsewhere/file.lua')
  eq(pane.display_path('/outside/home/file.lua'), '/outside/home/file.lua')
  eq(pane.display_path('/work/stringer-extra/a', '/work/stringer'), '/work/stringer-extra/a')
end)
test('cwd changes and navigation retain readable location endings', function()
  local r = capture(); yes(s.show())
  vim.api.nvim_set_current_dir(dir .. '/repo-a')
  assert(rows(r)[4]:find('a "quoted" file.lua:2', 1, true))
  yes(s.jump(2)); yes(s.show())
  assert(rows(r)[4]:find('a "quoted" file.lua:2', 1, true))
end)
test('missing and stale targets preserve active state', function()
  local r = capture(); yes(s.jump(1))
  vim.fn.delete(other); no(s.next()); eq(r.index, 1)
  vim.api.nvim_buf_set_lines(0, 2, -1, false, {})
  no(s.jump(3)); eq(r.index, 1)
end)
test('modified code obeys nohidden safeguards', function()
  local r = capture(); yes(s.jump(1)); vim.o.hidden = false
  vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'draft' })
  no(s.next()); eq(r.index, 1); eq(vim.api.nvim_buf_get_name(0), file)
  vim.o.hidden = true; yes(s.next()); eq(vim.bo[vim.fn.bufnr(file)].modified, true)
end)
test('pane retains most recent code window and fails with no code windows', function()
  capture(); vim.cmd('botright vsplit')
  local win = vim.api.nvim_get_current_win()
  yes(s.show()); yes(s.next()); eq(vim.api.nvim_get_current_win(), win)
  yes(s.show()); vim.cmd('only'); no(s.next())
end)
test('pane window selection stays within current tab and reuses buffers', function()
  local r = capture(); yes(s.show()); local buf = pane.buffer(r)
  vim.cmd('tabnew'); edit(other)
  local win = vim.api.nvim_get_current_win()
  yes(s.show()); yes(s.next()); eq(vim.api.nvim_get_current_win(), win)
  yes(s.open('demo')); eq(pane.buffer(state.active), buf)
end)
test('persisted paths reopen in a fresh Neovim process', function()
  local r = capture()
  local marks = vim.deepcopy(r.marks)
  marks[1].note = 'Persistent note\nSecond line'
  marks[3].skipped = true
  yes(require('stringer.model').persist(r, marks, nil))
  vim.env.STRINGER_REOPEN_DIR, vim.env.STRINGER_REOPEN_FILE = dir .. '/paths', file
  local output = vim.fn.system({ vim.v.progpath, '--headless', '-u', 'NONE', '-l', 'tests/reopen.lua' })
  assert(vim.v.shell_error == 0, output); assert(output:find('REOPEN PASS'), output)
end)

test('v1 reads without rewrite and upgrades on mutation; v2 metadata round trips', function()
  local r = capture()
  local lines = codec.encode(r.marks)
  lines[1] = '{"type":"stringer","format_version":1,"mark_version":1}'
  vim.fn.writefile(lines, r.file)
  local before = store.read(r.file)
  yes(s.reload()); eq(store.read(r.file), before)
  yes(s.skip(1)); assert(store.read(r.file):find('"mark_version":2', 1, true))
  local marks = { { file = file, line = 1, skipped = true, note = 'α\nsecond line\n', frame = 'original frame' } }
  eq(codec.decode(codec.encode(marks)), marks)
  lines = codec.encode(marks)
  lines[2] = lines[2]:gsub('"skipped":true', '"skipped":"bad"')
  no(codec.decode(lines))
end)
test('skipped marks are excluded from proximity and bounded cyclic navigation', function()
  local r = capture(); yes(s.skip(1)); yes(s.skip(2))
  vim.api.nvim_win_set_cursor(0, { 1, 0 }); s.sync(); eq(r.index, 3)
  yes(s.next()); eq(r.index, 3); yes(s.prev()); eq(r.index, 3)
  yes(s.skip(3)); no(s.next()); no(s.prev())
  yes(s.jump(1)); eq(r.index, 1)
  yes(s.show()); yes(s.hide_skipped()); eq(#r.marks, 3)
  assert(rows(r)[1]:find('3 hidden', 1, true))
  yes(s.hide_skipped()); yes(s.undo()); eq(r.marks[3].skipped, nil)
end)
test('hidden rows map actions correctly and filtered movement preserves hidden order', function()
  local r = capture(); yes(s.show()); yes(s.skip(2)); yes(s.hide_skipped())
  eq(r.row_to_index[3], 1); eq(r.row_to_index[4], 1); eq(r.row_to_index[5], 3)
  vim.api.nvim_win_set_cursor(0, { 3, 0 }); yes(s.move_down())
  eq(r.marks[1].file, other); eq(r.marks[1].skipped, true)
  eq(r.marks[2].line, 4); eq(r.marks[3].line, 2)
  eq(pane.selected(r), 3)
  yes(s.remove()); eq(#r.marks, 2); eq(r.marks[2].line, 4)
  yes(s.undo()); yes(s.undo()); eq(r.marks[2].skipped, true)
  vim.api.nvim_win_set_cursor(0, { 3, 0 }); yes(s.skip())
  eq(pane.selected(r), 3)
end)
test('hidden active mark has header indicator and view state is not persisted', function()
  local r = capture(); yes(s.show()); yes(s.skip(1)); yes(s.hide_skipped())
  yes(s.jump(1))
  assert(rows(r)[1]:find('active hidden', 1, true))
  eq(store.load('demo').hide_skipped, nil)
  yes(s.show()); vim.cmd('close'); yes(s.show()); eq(r.hide_skipped, true)
  yes(s.reload()); eq(state.active.hide_skipped, nil)
end)
test('multiline note saves, previews, undoes, and removes empty content', function()
  local r = capture(); yes(s.show()); yes(s.note(1))
  local notes = require('stringer.notes')
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'α note', 'second paragraph', '' })
  vim.cmd('write')
  eq(store.load('demo').marks[1].note, 'α note\nsecond paragraph\n')
  assert(rows(r)[3]:find('[note]', 1, true))
  yes(s.rename('renamed'))
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { '' }); vim.cmd('write')
  eq(store.load('renamed').marks[1].note, nil)
  yes(s.undo()); eq(r.marks[1].note, 'α note\nsecond paragraph\n')
  eq(notes.editor.record, r)
end)
test('stale note drafts cannot attach to reordered or reloaded marks', function()
  local r = capture(); yes(s.note(1))
  local editor = require('stringer.notes').editor
  vim.api.nvim_buf_set_lines(editor.buf, 0, -1, false, { 'draft' })
  yes(s.move_down(1))
  no(pcall(vim.cmd, 'wq')); eq(vim.api.nvim_win_is_valid(editor.win), true)
  eq(vim.bo[editor.buf].modified, true); eq(r.marks[2].note, nil)
  no(s.note(2))
  yes(s.reload()); no(require('stringer.notes').save())
end)
test('note failed writes preserve draft, history and file', function()
  local r = capture(); yes(s.note(1))
  local editor = require('stringer.notes').editor
  local before, history = r.text, #r.history
  vim.api.nvim_buf_set_lines(editor.buf, 0, -1, false, { 'draft' })
  local original = uv.fs_rename
  uv.fs_rename = function() return nil, 'injected failure' end
  local ok, err = pcall(function()
    no(pcall(vim.cmd, 'wq')); eq(vim.bo[editor.buf].modified, true)
    eq(r.text, before); eq(store.read(r.file), before); eq(#r.history, history)
  end)
  uv.fs_rename = original; yes(ok, err)
end)

local function fixture(name)
  local lines = vim.fn.readfile(cwd .. '/tests/fixtures/stacktraces/' .. name .. '.txt')
  for i, line in ipairs(lines) do lines[i] = line:gsub('@ROOT@', function() return dir end) end
  return lines
end
local function source(path)
  vim.fn.mkdir(vim.fs.dirname(path), 'p')
  vim.fn.writefile({ 'source' }, path)
end
local function resolve(parsed, root_dir)
  local result
  require('stringer.import.resolve').resolve(parsed, root_dir, {}, function(value) result = value end)
  yes(vim.wait(3000, function() return result ~= nil end, 5), 'resolution timed out')
  return result
end
test('Ruby example reverses frames and preserves repeated locations and context', function()
  local parsed = yes(require('stringer.import.parsers').parse(fixture('ruby'), 'ruby'))
  eq(#parsed.frames, 5); eq(parsed.frames[1].line, 1253)
  eq(parsed.frames[2].file, 'app/controllers/tasks_controller.rb')
  eq(parsed.frames[3].file, parsed.frames[2].file)
  eq(parsed.frames[2].line, 7); eq(parsed.frames[3].line, 7)
  source(dir .. '/gems/active_record/base.rb'); source(dir .. '/gems/action_controller/base.rb')
  source(dir .. '/app/controllers/tasks_controller.rb')
  local result = resolve(parsed, dir)
  eq(#result.marks, 5); eq(#result.issues, 0)
  assert(result.marks[2].frame:find('show', 1, true)); assert(result.marks[3].frame:find('new', 1, true))
end)
test('V8 JavaScript and TypeScript resolve local files in caller-first order', function()
  source(dir .. '/src/worker.ts'); source(dir .. '/src/view.tsx'); source(dir .. '/src/main.js')
  local parser = require('stringer.import.parsers')
  eq(parser.detect(fixture('v8')), { 'javascript' })
  local parsed = yes(parser.parse(fixture('v8'), 'javascript'))
  local result = resolve(parsed, dir)
  eq(#result.marks, 3); eq(result.marks[1].file, dir .. '/src/main.js')
  eq(result.marks[3].line, 12)
end)
test('Java nested classes use package narrowing and report ambiguous or missing sources', function()
  source(dir .. '/src/app/Service.java'); source(dir .. '/src/app/Main.java')
  source(dir .. '/src/elsewhere/Service.java')
  local parsed = yes(require('stringer.import.parsers').parse(fixture('java'), 'java'))
  local result = resolve(parsed, dir)
  eq(#result.marks, 2); eq(result.marks[2].file, dir .. '/src/app/Service.java')
  source(dir .. '/other/app/Service.java')
  result = resolve(parsed, dir)
  eq(#result.marks, 1); eq(#result.issues, 1); eq(#result.issues[1].candidates, 2)
  vim.fn.delete(dir .. '/src/app/Main.java')
  result = resolve(parsed, dir); eq(#result.marks, 0); eq(#result.issues, 2)
end)
test('parser rejects chains, mixed stacks and outermost-first Ruby headers', function()
  local parser = require('stringer.import.parsers')
  no(parser.parse({ 'at app.Main.main(Main.java:1)', 'Caused by: failure', 'at app.Main.run(Main.java:2)' }, 'java'))
  no(parser.parse({ 'at a (/tmp/a.js:1:2)', 'Error: second stack', 'at b (/tmp/b.js:2:1)' }, 'javascript'))
  no(parser.parse({ 'Traceback (most recent call last):', '/tmp/a.rb:1:in `main\'' }, 'ruby'))
end)
test('native and nonlocal frames are reported while local file URIs resolve', function()
  local parser = require('stringer.import.parsers')
  local parsed = yes(parser.parse({ 'at native (native)', 'at web (https://example.com/a.js:1:2)',
    'at local (file://' .. file:gsub(' ', '%%20') .. ':2:3)' }, 'javascript'))
  local result = resolve(parsed, dir)
  eq(#result.marks, 1); eq(result.marks[1].file, file); eq(#result.issues, 2)
end)
test('import preserves trace and quickfix, persists once, and creates a new path', function()
  local previous = capture()
  source(dir .. '/gems/active_record/base.rb'); source(dir .. '/gems/action_controller/base.rb')
  source(dir .. '/app/controllers/tasks_controller.rb')
  vim.api.nvim_set_current_dir(dir)
  vim.cmd('enew'); local buf = vim.api.nvim_get_current_buf()
  local lines = fixture('ruby'); vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.fn.setqflist({ { filename = file, lnum = 2, text = 'keep' } })
  local quickfix = vim.fn.getqflist({ all = 0 })
  local original, writes = store.write, 0
  store.write = function(...) writes = writes + 1; return original(...) end
  local ok, err = pcall(function()
    yes(s.import('trace')); eq(state.active.name, 'trace'); eq(#state.active.marks, 5)
    eq(writes, 1); eq(vim.fn.getqflist({ all = 0 }), quickfix)
    eq(vim.api.nvim_buf_get_lines(buf, 0, -1, false), lines)
    eq(#store.load(previous.name).marks, 3)
  end)
  store.write = original; yes(ok, err)
end)
test('partial import reports excluded frames and zero results create nothing', function()
  capture(); vim.cmd('enew')
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'at valid (' .. file .. ':2:1)', 'at missing (/missing.js:1:2)' })
  yes(s.import('partial')); eq(#state.active.marks, 1)
  assert(require('stringer.import').report[1]:find('partial', 1, true))
  vim.cmd('enew'); vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'at missing (/missing.js:1:2)' })
  yes(s.import('empty')); no(store.load('empty')); eq(state.active.name, 'partial')
end)
test('cancelled import prompt and name collisions preserve the active path', function()
  local r = capture(); vim.cmd('enew')
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'at local (' .. file .. ':2:1)' })
  local original = vim.ui.input
  local ok, err = pcall(function()
    vim.ui.input = function(_, callback) callback(nil) end
    yes(s.import()); eq(state.active, r)
    yes(s.import('demo')); eq(state.active, r)
    local callback
    vim.ui.input = function(_, cb) callback = cb end
    yes(s.import()); yes(s.cancel_import()); callback('cancelled')
    no(store.load('cancelled')); eq(state.active, r)
  end)
  vim.ui.input = original; yes(ok, err)
end)
test('import write failure leaves no new file and preserves active path', function()
  local r = capture(); vim.cmd('enew')
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'at local (' .. file .. ':2:1)' })
  local original = uv.fs_rename
  uv.fs_rename = function() return nil, 'injected import failure' end
  local ok, err = pcall(function()
    yes(s.import('failed')); eq(state.active, r); no(store.load('failed'))
    assert(require('stringer.import').report[1]:find('not saved', 1, true))
  end)
  uv.fs_rename = original; yes(ok, err)
end)
test('reloading a visible filtered path rebuilds rows for the new snapshot', function()
  local r = capture(); yes(s.show()); yes(s.skip(2)); yes(s.hide_skipped())
  vim.fn.writefile(codec.encode({ { file = other, line = 1, note = 'replacement' } }), r.file)
  yes(s.reload())
  eq(state.active.row_to_index[3], 1); eq(state.active.row_to_index[4], 1)
  assert(rows(state.active)[3]:find('[note]', 1, true))
  yes(s.jump(1)); assert(table.concat(rows(state.active), '\n'):find('replacement', 1, true))
  eq(state.active.hide_skipped, nil)
end)
test('Java indexing yields and can be cancelled without creating a path', function()
  for i = 1, 140 do source(dir .. '/project/pkg/File' .. i .. '.java') end
  vim.api.nvim_set_current_dir(dir)
  vim.cmd('enew'); vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'at pkg.File1.main(File1.java:1)' })
  yes(s.import('cancelled')); yes(s.cancel_import()); vim.wait(30)
  no(store.load('cancelled')); eq(state.active, nil)
end)

test('two-line layout preserves suffixes, Unicode widths, and row ownership', function()
  local layout = require('stringer.layout')
  local r = { name = 'layout', index = 1, marks = {
    { file = '/one/controllers/任务_controller.rb', line = 123, note = 'alpha\n\nlong words long words long words' },
    { file = '/two/models/任务_controller.rb', line = 8 },
  } }
  local suffixes = layout.suffixes(r.marks)
  eq(suffixes[r.marks[1].file], 'controllers/任务_controller.rb')
  eq(suffixes[r.marks[2].file], 'models/任务_controller.rb')
  for _, width in ipairs({ 1, 4, 12, 24, 48 }) do
    local view = layout.build(r, width, function() return 'VeryLongEnclosingFunction' end, true)
    for row = 3, #view.lines do
      assert(vim.fn.strdisplaywidth(view.lines[row]) <= width, view.lines[row])
      assert(view.row_to_index[row])
    end
    eq(view.row_to_index[view.ranges[1].location], 1)
    eq(view.row_to_index[view.ranges[1].last], 1)
    if width >= 12 then assert(view.lines[4]:sub(-4) == ':123') end
  end
end)
test('inline notes follow the active mark and preserve selection across reflow', function()
  local r = capture()
  local marks = vim.deepcopy(r.marks)
  marks[1].note, marks[2].note = 'First\n\nMore', 'Second'
  yes(require('stringer.model').persist(r, marks, 1))
  yes(s.show()); yes(s.jump(1)); yes(s.show())
  eq(r.ranges[1].last - r.ranges[1].location, 3)
  vim.api.nvim_win_set_cursor(0, { r.index_to_row[3] + 1, 0 })
  local win = vim.api.nvim_get_current_win()
  r.index = 2; require('stringer.presentation').refresh(r)
  eq(pane.selected(r), 3); eq(vim.api.nvim_get_current_win(), win)
  eq(r.ranges[1].last, r.ranges[1].location)
  eq(r.ranges[2].last, r.ranges[2].location + 1)
  vim.api.nvim_win_set_cursor(0, { r.ranges[2].last, 0 }); eq(pane.selected(r), 2)
  yes(s.remove()); eq(#r.marks, 2); eq(r.marks[2].line, 4)
end)
test('automatic note refresh does not modify an open note draft', function()
  local r = capture(); yes(s.note(1))
  local editor = require('stringer.notes').editor
  vim.api.nvim_buf_set_lines(editor.buf, 0, -1, false, { 'unsaved draft' })
  local revision = r.revision
  r.index = 2; require('stringer.presentation').refresh(r)
  eq(vim.bo[editor.buf].modified, true)
  eq(vim.api.nvim_buf_get_lines(editor.buf, 0, -1, false), { 'unsaved draft' })
  eq(r.revision, revision); yes(require('stringer.notes').save())
  eq(r.marks[1].note, 'unsaved draft')
end)
test('shared pane uses narrowest visible width without losing selected mark', function()
  local r = capture(); yes(s.show())
  local first = vim.api.nvim_get_current_win()
  vim.api.nvim_win_set_cursor(first, { r.index_to_row[2] + 1, 0 })
  vim.cmd('tabnew'); yes(s.show())
  local second = vim.api.nvim_get_current_win()
  vim.api.nvim_win_set_width(second, 22)
  require('stringer.presentation').refresh(r)
  eq(r.row_to_index[vim.api.nvim_win_get_cursor(first)[1]], 2)
  local available = vim.api.nvim_win_get_width(second) - vim.fn.getwininfo(second)[1].textoff
  assert(pane.width(r) <= available)
  for _, range in pairs(r.ranges) do assert(vim.fn.strdisplaywidth(rows(r)[range.location]) <= available) end
end)

local function signs(buf)
  local result = {}
  for _, mark in ipairs(vim.api.nvim_buf_get_extmarks(buf, require('stringer.gutter').namespace, 0, -1, { details = true })) do
    result[mark[2] + 1] = mark[4]
  end
  return result
end
test('source signs aggregate duplicate notes, active and mixed skipped states', function()
  local r = capture()
  local marks = vim.deepcopy(r.marks)
  marks[1].skipped, marks[1].note = true, 'note'
  marks[4] = { file = file, line = 2 }
  yes(require('stringer.model').persist(r, marks, 4))
  local buf = vim.fn.bufnr(file)
  eq(signs(buf)[2].sign_text:match('^%S+'), 'N')
  eq(signs(buf)[2].sign_hl_group, 'StringerGutterActive')
  r.index = 3; require('stringer.presentation').refresh(r)
  eq(signs(buf)[2].sign_hl_group, 'StringerGutter')
  yes(s.skip(4)); eq(signs(buf)[2].sign_hl_group, 'StringerGutterSkipped')
  yes(s.undo()); eq(signs(buf)[2].sign_hl_group, 'StringerGutter')
  yes(s.new('empty')); eq(signs(buf), {})
end)
test('signs retain fixed stored lines after edits and leave other namespaces alone', function()
  local r = capture(); local buf = vim.fn.bufnr(file)
  local text = r.text
  local ns = vim.api.nvim_create_namespace('test.other-sign')
  vim.api.nvim_buf_set_extmark(buf, ns, 1, 0, { sign_text = 'X', priority = 100 })
  vim.api.nvim_buf_set_lines(buf, 0, 0, false, { 'inserted' })
  yes(vim.wait(500, function() return signs(buf)[2] ~= nil and signs(buf)[4] ~= nil end, 5))
  eq(#vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {}), 1)
  eq(r.text, text); eq(store.read(r.file), text)
  vim.api.nvim_buf_set_lines(buf, 1, -1, false, {})
  yes(vim.wait(500, function() return next(signs(buf)) == nil end, 5))
end)
test('source unload and reload recreate only the active codepath indicators', function()
  capture(); local buf = vim.fn.bufnr(file)
  vim.api.nvim_buf_delete(buf, { unload = true, force = true })
  yes(s.new('empty'))
  edit(file)
  eq(signs(vim.api.nvim_get_current_buf()), {})
  yes(s.open('demo'))
  assert(signs(vim.api.nvim_get_current_buf())[2])
end)
test('disabled UI options leave storage and other editor layout settings unchanged', function()
  local r = capture(); local buf = vim.fn.bufnr(file)
  local signcolumn = vim.wo.signcolumn
  s.setup({ gutter = false, inline_notes = false, symbol_labels = false })
  eq(signs(buf), {}); eq(vim.wo.signcolumn, signcolumn)
  local marks = vim.deepcopy(r.marks); marks[1].note = 'Hidden inline note'
  yes(require('stringer.model').persist(r, marks, 1)); yes(s.show())
  eq(r.ranges[1].last, r.ranges[1].location)
  no(pcall(s.setup, { gutter_sign = 'too wide' }))
end)
test('frame labels retain distinct Ruby contexts and parse V8 and Java titles', function()
  local labels = require('stringer.labels')
  eq(labels.frame("app/task.rb:7:in `show'"), 'show')
  eq(labels.frame("app/task.rb:7:in `new'"), 'new')
  eq(labels.frame('at async main (/app/main.ts:2:3)'), 'async main')
  eq(labels.frame('at module/app.Service.run(Service.java:4)'), 'app.Service.run')
  eq(labels.frame('at /app/main.ts:2:3'), nil)
end)
local function symbol(name, kind, start_line, end_line, end_col, children)
  return { name = name, kind = kind, range = {
    start = { line = start_line, character = 0 }, ['end'] = { line = end_line, character = end_col or 0 },
  }, children = children }
end
test('enclosing symbols choose nested methods and respect end-exclusive ranges', function()
  local labels = require('stringer.labels')
  local symbols = { symbol('Service', 5, 0, 20, 0, {
    symbol('run', 6, 2, 10, 0, { symbol('nested', 12, 4, 6, 0) }),
  }) }
  eq(labels.enclosing(symbols, 3), 'Service.run')
  eq(labels.enclosing(symbols, 5), 'Service.nested')
  eq(labels.enclosing(symbols, 6), 'Service.run')
  eq(labels.enclosing(symbols, 10), nil)
  eq(labels.enclosing({ { name = 'flat', kind = 6, location = {} } }, 2), nil)
end)
test('LSP title cache coalesces requests and rejects stale edit responses', function()
  local r = capture(); local buf = vim.fn.bufnr(file)
  local labels = require('stringer.labels')
  local original = vim.lsp.get_clients
  local callbacks, requests = {}, 0
  local client = { id = 7 }
  client.supports_method = function() return true end
  client.request = function(...)
    local args = { ... }
    local callback = args[vim.fn.has('nvim-0.11') == 1 and 4 or 3]
    requests = requests + 1; callbacks[#callbacks + 1] = callback
    return true, requests
  end
  local ok, err = pcall(function()
    vim.lsp.get_clients = function() return { client } end
    labels.invalidate(buf)
    labels.request(buf, function() end); labels.request(buf, function() end); eq(requests, 1)
    vim.api.nvim_buf_set_lines(buf, 0, 1, false, { 'edit' })
    callbacks[1](nil, { symbol('stale', 12, 0, 20) })
    eq(labels.title(r.marks[1]), vim.fs.basename(file))
    labels.request(buf, function() end)
    callbacks[#callbacks](nil, { symbol('current', 12, 0, 20) })
    eq(labels.title(r.marks[1]), 'current')
    vim.lsp.get_clients = function() return {} end
    labels.request(buf, function() end)
    eq(labels.title(r.marks[1]), vim.fs.basename(file))
  end)
  vim.lsp.get_clients = original; yes(ok, err)
end)
test('delayed LSP results do not redraw an unrelated active path or move focus', function()
  capture(); local buf = vim.fn.bufnr(file)
  local labels = require('stringer.labels')
  local original, callback = vim.lsp.get_clients, nil
  local client = { id = 8, supports_method = function() return true end }
  client.request = function(...)
    local args = { ... }; callback = args[vim.fn.has('nvim-0.11') == 1 and 4 or 3]
    return true, 1
  end
  local ok, err = pcall(function()
    vim.lsp.get_clients = function() return { client } end
    labels.invalidate(buf)
    require('stringer.presentation').labels(buf, state.active)
    assert(callback)
    yes(s.new('unrelated')); yes(s.show())
    local win, before = vim.api.nvim_get_current_win(), rows(state.active)
    callback(nil, { symbol('late', 12, 0, 20) }); vim.wait(20)
    eq(state.active.name, 'unrelated'); eq(rows(state.active), before)
    eq(vim.api.nvim_get_current_win(), win)
  end)
  vim.lsp.get_clients = original; yes(ok, err)
end)

vim.api.nvim_set_current_dir(cwd)
vim.fn.delete(root, 'rf')
print(('%d passed, %d failed'):format(passed, failed))
vim.cmd(failed == 0 and 'qa!' or 'cquit 1')
